[package]
name = "AviCore"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["json", "default-tls"] }
tokio = { version = "1.35", features = ["full"] }
serde_json = "1.0.147"
serde = { version = "1.0.228", features = ["derive"] }
dyon = "0.51.0"
serde_yaml = "0.9.34"
anyhow = "1.0.100"
rand = "0.9.2"
sha2 = "0.11.0-rc.3"
hmac = "0.13.0-rc.3"
hex = "0.4.3"
chrono = "0.4.42"
humantime = "2.3.0"
avi_device = { package = "avi-device", git = "https://github.com/apoll011/avi-device" }

[dev-dependencies]
async-trait = "0.1.89"
avi-p2p = { git = "https://github.com/apoll011/avi-device", package = "avi-p2p" }