[package]
name = "AviCore"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["json", "default-tls"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
dyon = "0.49.2"
read_token = "*"
once_cell = "1.21.3"
ctor = "0.2"
inventory = "0.3"
