[package]
name = "AviCore"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["json", "default-tls"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
dyon = "0.50.1"
serde_yaml = "0.9.34+deprecated"
anyhow = "1.0.100"
rand = "0.6.5"
