id: "saudation"
name: "Saudation"
description: "A skill to say hello in various languages."
entry: "main.avi"
capabilities:
  - "intent:light.turn_on"
  - "intent:light.turn_off"
permissions:
  - "speak"
  - "display"
subscription:
  - "topic:intent/parse/text"
author: "Avi Labs"
version: "1.0.0"