[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[env]
# OPENSSL_DIR = { value = "/opt/homebrew/opt/openssl@3", force = false }
# PKG_CONFIG_PATH = { value = "/opt/homebrew/opt/openssl@3/lib/pkgconfig", force = false }
